// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygfphvvfgmmfeiqffznr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZnBodnZmZ21tZmVpcWZmem5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTE4NzUsImV4cCI6MjA2ODQ4Nzg3NX0.m_o4B1_sExAXN6vRKMuxCKkFyyDTZtoeZsBvSiXrUng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});